[package]
name = "superman"
version = "20.11.3"
authors = ["FeÌlix Saparelli <felix@passcod.name>"]
edition = "2018"

# See more keys and their definitions at https://doc.rust-lang.org/cargo/reference/manifest.html

[dependencies]
async-std = { version = "1.7.0", features = ["attributes"] }
color-eyre = "0.5.8"
deku = "0.9.1"
hostname = "0.3.1"
uuid = { version = "0.8", features = ["v4"] }

[profile.dev.package.backtrace]
opt-level = 3
